let names = prompt("what is your full name");
let age = prompt("how old are you");
let grade = prompt("what is your grade status");
let subjects = prompt("what is your favourite subjects");
let grades = prompt("what is your grades");
let averageGrade = prompt("what is your averageGrade");
let highestGrade = prompt("what is your highestGrade");
let lowestGrade = prompt("what is your lowestGrade");
let address = prompt("where is your address");
let phonenumber = prompt("what is your phone number");
let email = prompt("what is your email");
let courses = prompt("what is your course");
let city = prompt("what is your city");
let isMarried = prompt("Are you married");
let hobbies = prompt("what is your hobbie");
let familyStatus = prompt("How much is your family status");
let familyMembers = prompt("How much is your family members");
let siblings = prompt("what is your sibling");
let studentoff = prompt("what is student off");

console.log(names);
console.log(age);
console.log(grade);
console.log(subjects);